version: '3'

services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - webnet

  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
